### ISSUE TITLE
Add about command that mentions current version

### ISSUE THREAD

**Issue by maikdevries** [maikdevries/Lunar#22]
**Is your feature request related to a problem? Please describe.**
There is no way to tell what version of the bot is currently running, this should be part of the `about` command. In addition, some other statistics could be added such as invite link, and others.

**Describe the solution you'd like**
Add a brief `about` command which at least mentions the current version of the bot and has the invite link.

**Comment by julxyz** [comment]
It would be useful not only to mention the version but also the commit it's running on. Make the bot cache the directories current commit on startup.
