### ISSUE TITLE
Improve 8ball responses

### ISSUE THREAD

**Issue by julxyz** [maikdevries/Lunar#53]
**Is your improvement request related to a problem? Please describe.**
8ball sends answers whenever a message is edited aswell. This can lead to spam. If multiple users ask questions at once confusion can also arise which question the 8ball answers.

**Describe the solution you'd like**
1) limit responses to original message and max 1 edit
2) bot should quote question asked in the response
```
> @user asks: blasdlasldas
8ball says: no
```

**bonus doggo**
![image](https://user-images.githubusercontent.com/45462701/84408560-95bd0800-ac0c-11ea-87b3-56f9d10c7098.png)

**Comment by maikdevries** [comment]
I've decided to limit the number of edits to 3 and thus on the fourth attempt it will return a new error message:

> **Excuse me**, third time wasn't the charm for you. Please send a new message instead of editing the original.

In addition, replies to the question now quote the original question asked at the time.
