### ISSUE TITLE
Add a "develop" branch

### ISSUE THREAD

**Issue by julxyz** [maikdevries/Lunar#6]
Commits should not be made directly to master.

**Comment by maikdevries** [comment]
I'd agree with you if I would send out new features in small commits, therefore cluttering the master branch with these 'meaningless' commits. However, for this project, I don't see the added value of a dev branch just yet.

I'm not auto-building from the master branch, I'm not pushing small commits, and working on master directly makes sure that there's a level of confidence in each commit before pushing it.

I'll consider adding a dev branch as soon I see reason to, but as of now, there's no added benefit just yet, at least with my workflow.
