### ISSUE TITLE
Add 'Currently Livestreaming' role to members that are currently streaming

### ISSUE THREAD

**Issue by maikdevries** [maikdevries/Lunar#7]
This will move people that currently have the 'streamer/content creator/etc.' role up to a 'Currently livestreaming' role whenever they start streaming and remove the role when they stop streaming.

This will allow these content creators to be more exposed given that the role has higher priority over their default content creator role.

This should only work for members that have a predefined role [streamers/content creators] which should be set in the config to avoid every member that starts a stream from getting the elevated role.

**Comment by julxyz** [comment]
That sounds like a really cool concept 💜
